#!/bin/sh
#
# Create an upstream tarball from the language pack xpi

XPI=lightning.xpi
SRCPKG="iceowl-l10n"

case $1 in
	-d)
		DOWNLOAD=1
		shift
		;;
	*)
		;;
esac

if [ -n "$1" ]; then
	VERSION=$1
else
	echo "Missing version."
	exit 1
fi

ORIGDIR="${SRCPKG}-${VERSION}/"

if [ -d ${ORIGDIR} ]; then
	echo "${ORIGDIR} exists, giving up."
	exit 1
fi

[ -z "${DOWNLOAD}" ] || wget -O${XPI} http://releases.mozilla.org/pub/mozilla.org/calendar/lightning/releases/${VERSION}/linux/${XPI}

mkdir ${ORIGDIR}

tmpdir=$(mktemp -d)
unzip -d $tmpdir ${XPI}

ICEDOVE_VER=$(grep -A2 '{3550f703-e582-4d05-9a08-453d09bdfdc6}' $tmpdir/install.rdf)
ICEAPE_VER=$(grep -A2 '{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}' $tmpdir/install.rdf)

for jar in $tmpdir/chrome/*-*.jar; do 
	lang=$(echo $jar | sed -e 's,.*/[a-z]\+-\(.*\)\.jar,\1,')
	unzip -d $ORIGDIR/${lang} ${jar}
done
# shipped with the iceowl already
rm -rf ${ORIGDIR}en-US

tar cjf ${SRCPKG}_${VERSION}.orig.tar.bz2 ${ORIGDIR}

rm -rf $tmpdir

echo "Icedove version information"
echo ${ICEDOVE_VER}

echo "Iceape version information"
echo ${ICEAPE_VER}

echo "done."
